# Generated by Django 6.1.1 on 2026-09-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('telephone_numbers', models.CharField(max_length=100)),
                ('authorizer', models.CharField(max_length=150)),
                ('case_type', models.CharField(max_length=100)),
                ('personal_identifications', models.CharField(max_length=255)),
                ('attached_document', models.FileField(blank=True, upload_to='case_documents/')),
                ('start_date', models.DateField()),
                ('first_termination_date', models.DateField(blank=True, null=True)),
                ('reprovisioned', models.BooleanField(default=False)),
                ('second_termination_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_date', 'code'],
            },
        ),
    ]
