# Generated by Django 6.1.1 on 2026-09-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminbackup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caserecord',
            name='personal_identifications',
            field=models.ImageField(upload_to='personal_identifications/', verbose_name='Personal identification image'),
        ),
    ]
