# Generated by Django 6.1.1 on 2026-09-29 06:29

import django.db.models.deletion
from django.db import migrations, models


def copy_existing_numbers(apps, schema_editor):
    database = schema_editor.connection.alias
    CaseRecord = apps.get_model('Adminbackup', 'CaseRecord')
    CasePhoneNumber = apps.get_model('Adminbackup', 'CasePhoneNumber')

    for case in CaseRecord.objects.using(database).all().iterator():
        number = case.telephone_numbers
        if number and number.strip():
            CasePhoneNumber.objects.using(database).create(
                case_record_id=case.pk,
                number=number,
            )


def restore_existing_numbers(apps, schema_editor):
    database = schema_editor.connection.alias
    CaseRecord = apps.get_model('Adminbackup', 'CaseRecord')
    CasePhoneNumber = apps.get_model('Adminbackup', 'CasePhoneNumber')

    for case in CaseRecord.objects.using(database).all().iterator():
        numbers = CasePhoneNumber.objects.using(database).filter(
            case_record_id=case.pk
        )
        case.telephone_numbers = ', '.join(
            f'{phone.label}: {phone.number}' if phone.label else phone.number
            for phone in numbers
        )[:100]
        case.save(using=database, update_fields=['telephone_numbers'])


class Migration(migrations.Migration):

    dependencies = [
        ('Adminbackup', '0002_alter_caserecord_personal_identifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caserecord',
            name='telephone_numbers',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='CasePhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=50)),
                ('number', models.CharField(max_length=100)),
                ('case_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='Adminbackup.caserecord')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(copy_existing_numbers, restore_existing_numbers),
        migrations.RemoveField(
            model_name='caserecord',
            name='telephone_numbers',
        ),
    ]
