# Generated by Django 6.1.1 on 2026-09-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminbackup', '0003_remove_caserecord_telephone_numbers_casephonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='casephonenumber',
            name='reprovisioned',
            field=models.BooleanField(default=False, verbose_name='Target reprovisioned'),
        ),
        migrations.AlterField(
            model_name='caserecord',
            name='reprovisioned',
            field=models.BooleanField(default=False, verbose_name='Case reprovisioned'),
        ),
    ]
