# Generated by Django 6.1.1 on 2026-09-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminbackup', '0004_casephonenumber_reprovisioned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casephonenumber',
            name='reprovisioned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Reprovisioned on'),
        ),
    ]
