# Generated by Django 6.1.1 on 2026-09-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminbackup', '0005_casephonenumber_reprovisioned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='caserecord',
            name='reprovisioned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Reprovisioned on'),
        ),
        migrations.AlterField(
            model_name='casephonenumber',
            name='reprovisioned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Target reprovisioned on (legacy)'),
        ),
    ]
