# Generated by Django 6.1.1 on 2026-09-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminbackup', '0006_caserecord_reprovisioned_date_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='casephonenumber',
            constraint=models.UniqueConstraint(fields=('case_record', 'number'), name='unique_target_number_per_case'),
        ),
    ]
