# Generated by Django 6.1.1 on 2026-10-01 15:17

from django.db import migrations, models


def populate_serial_numbers(apps, schema_editor):
	database = schema_editor.connection.alias
	CaseRecord = apps.get_model("Adminbackup", "CaseRecord")

	record_ids = list(
		CaseRecord.objects.using(database).values_list("pk", flat=True)
	)
	for record_id in record_ids:
		CaseRecord.objects.using(database).filter(pk=record_id).update(
			serial_number=str(record_id)
		)


class Migration(migrations.Migration):

    dependencies = [
        ('Adminbackup', '0010_target_record_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caserecord',
            options={'ordering': ['pk']},
        ),
		migrations.RunPython(populate_serial_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='caserecord',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='S/N'),
        ),
    ]
