# Generated by Django 6.1.1 on 2026-10-01 16:15

from django.db import migrations


def move_telephone_numbers_to_phone_entries(apps, schema_editor):
	database = schema_editor.connection.alias
	CaseRecord = apps.get_model("Adminbackup", "CaseRecord")
	CasePhoneNumber = apps.get_model("Adminbackup", "CasePhoneNumber")

	for record in CaseRecord.objects.using(database).only(
		"pk", "telephone_number"
	).iterator():
		number = record.telephone_number.strip()
		if not number:
			continue

		existing_numbers = CasePhoneNumber.objects.using(database).filter(
			case_record_id=record.pk
		).values_list("number", flat=True)
		normalized_number = "".join(
			character for character in number if character.isdigit()
		)
		if not any(
			"".join(character for character in existing if character.isdigit())
			== normalized_number
			for existing in existing_numbers
		):
			CasePhoneNumber.objects.using(database).create(
				case_record_id=record.pk,
				label="",
				number=number,
			)


def restore_telephone_numbers(apps, schema_editor):
	database = schema_editor.connection.alias
	CaseRecord = apps.get_model("Adminbackup", "CaseRecord")
	CasePhoneNumber = apps.get_model("Adminbackup", "CasePhoneNumber")

	for record in CaseRecord.objects.using(database).iterator():
		first_number = (
			CasePhoneNumber.objects.using(database)
			.filter(case_record_id=record.pk)
			.order_by("pk")
			.values_list("number", flat=True)
			.first()
		)
		if first_number:
			record.telephone_number = first_number
			record.save(using=database, update_fields=["telephone_number"])


class Migration(migrations.Migration):

    dependencies = [
        ('Adminbackup', '0012_compact_target_serial_numbers'),
    ]

    operations = [
		migrations.RunPython(
			move_telephone_numbers_to_phone_entries,
			restore_telephone_numbers,
		),
        migrations.RemoveField(
            model_name='caserecord',
            name='telephone_number',
        ),
    ]
