# Generated by Django 6.1.1 on 2026-10-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminbackup', '0014_user_dashboard_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDashboardProfile',
        ),
    ]
